from ctypes import c_void_p, c_int, c_uint64

WormContext = c_void_p
WormInfo = c_void_p
WormEntry = c_void_p
WormTransactionResponse = c_void_p

WormError = c_int




(WORM_INIT_UNINITIALIZED,
WORM_INIT_INITIALIZED,
WORM_INIT_DECOMMISSIONED) = range(3)


# constants for WormUserId
WORM_USER_UNAUTHENTICATED = 0
WORM_USER_ADMIN = 1
WORM_USER_TIME_ADMIN = 2

WORM_EXPORT_TAR_INCREMENTAL_STATE_SIZE = 16

WORM_ERROR_NOERROR = 0
WORM_ERROR_INVALID_PARAMETER = 1
WORM_ERROR_NO_WORM_CARD = 2
WORM_ERROR_IO = 3
WORM_ERROR_TIMEOUT = 4
WORM_ERROR_OUTOFMEM = 5
WORM_ERROR_INVALID_RESPONSE = 6
WORM_ERROR_STORE_FULL_INTERNAL = 7
WORM_ERROR_RESPONSE_MISSING = 8
WORM_ERROR_EXPORT_NOT_INITIALIZED = 9
WORM_ERROR_EXPORT_FAILED = 10
WORM_ERROR_INCREMENTAL_EXPORT_INVALID_STATE = 11
WORM_ERROR_INCREMENTAL_EXPORT_NO_DATA = 12
WORM_ERROR_POWER_CYCLE_DETECTED = 13
WORM_ERROR_FIRMWARE_UPDATE_NOT_APPLIED = 14
WORM_ERROR_FROM_CARD_FIRST = 0x1000
WORM_ERROR_UNKNOWN = 0x1001
WORM_ERROR_NO_TIME_SET = 0x1002
WORM_ERROR_NO_TRANSACTION_IN_PROGRESS = 0x1004
WORM_ERROR_INVALID_CMD_SYNTAX = 0x1005
WORM_ERROR_WRONG_LENGTH = WORM_ERROR_INVALID_CMD_SYNTAX
WORM_ERROR_NOT_ENOUGH_DATA_WRITTEN = 0x1006
WORM_ERROR_TSE_INVALID_PARAMETER = 0x1007
WORM_ERROR_TRANSACTION_NOT_STARTED = 0x1008
WORM_ERROR_MAX_PARALLEL_TRANSACTIONS = 0x1009
WORM_ERROR_CERTIFICATE_EXPIRED = 0x100a
WORM_ERROR_NO_LAST_TRANSACTION = 0x100c
WORM_ERROR_CMD_NOT_ALLOWED = 0x100d
WORM_ERROR_TRANSACTION_SIGNATURES_EXCEEDED = 0x100e
WORM_ERROR_NOT_AUTHORIZED = 0x100f
WORM_ERROR_MAX_REGISTERED_CLIENTS_REACHED = 0x1010
WORM_ERROR_CLIENT_NOT_REGISTERED = 0x1011
WORM_ERROR_EXPORT_UNACKNOWLEDGED_DATA = 0x1012
WORM_ERROR_CLIENT_HAS_UNFINISHED_TRANSACTIONS = 0x1013
WORM_ERROR_TSE_HAS_UNFINISHED_TRANSACTIONS = 0x1014
WORM_ERROR_TSE_NO_RESPONSE_TO_FETCH = 0x1015
WORM_ERROR_NOT_ALLOWED_EXPORT_IN_PROGRESS = 0x1016
WORM_ERROR_STORE_FULL = 0x1017
WORM_ERROR_WRONG_STATE_NEEDS_PUK_CHANGE = 0x1050
WORM_ERROR_WRONG_STATE_NEEDS_PIN_CHANGE = 0x1051
WORM_ERROR_WRONG_STATE_NEEDS_ACTIVE_CTSS = 0x1053
WORM_ERROR_WRONG_STATE_NEEDS_ACTIVE_ERS = WORM_ERROR_WRONG_STATE_NEEDS_ACTIVE_CTSS
WORM_ERROR_WRONG_STATE_NEEDS_SELF_TEST = 0x1054
WORM_ERROR_WRONG_STATE_NEEDS_SELF_TEST_PASSED = 0x1055
WORM_ERROR_FWU_INTEGRITY_FAILURE = 0x1061
WORM_ERROR_FWU_DECRYPTION_FAILURE = 0x1062
WORM_ERROR_FWU_WRONG_FORMAT = 0x1064
WORM_ERROR_FWU_INTERNAL_ERROR = 0x1065
WORM_ERROR_FWU_DOWNGRADE_PROHIBITED = 0x1067
WORM_ERROR_TSE_ALREADY_INITIALIZED = 0x10FD
WORM_ERROR_TSE_DECOMMISSIONED = 0x10FE
WORM_ERROR_TSE_NOT_INITIALIZED = 0x10FF
WORM_ERROR_AUTHENTICATION_FAILED = 0x1100
WORM_ERROR_AUTHENTICATION_PIN_BLOCKED = 0x1201
WORM_ERROR_AUTHENTICATION_USER_NOT_LOGGED_IN = 0x1202
WORM_ERROR_SELF_TEST_FAILED_FW = 0x1300
WORM_ERROR_SELF_TEST_FAILED_CSP = 0x1310
WORM_ERROR_SELF_TEST_FAILED_RNG = 0x1320
WORM_ERROR_FWU_BASE_FW_ERROR = 0x1400
WORM_ERROR_FWU_FWEXT_ERROR = 0x1500
WORM_ERROR_FWU_CSP_ERROR = 0x1600
WORM_ERROR_EXPORT_NONE_IN_PROGRESS = 0x2001
WORM_ERROR_EXPORT_RETRY = 0x2002
WORM_ERROR_EXPORT_NO_DATA_AVAILABLE = 0x2003
WORM_ERROR_CMD_NOT_FOUND = 0xf000
WORM_ERROR_SIG_ERROR = 0xff00
WORM_ERROR_FROM_CARD_LAST = 0xFFFF

