# TSE Connection Library
# Copyright (C) 2020 Bernd Wurst <bernd@mosterei-wurst.de>
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

from wormtypes import *

class WormException(Exception):
    def __init__(self, errno, message):
        self.errno = errno
        self.message = message
        
    def __repr__(self):
        return '%s: %s' % (self.errno.hex(), self.message)


def WormError_to_exception(errno):
    if errno == WORM_ERROR_NOERROR:
        return None
    else:
        raise WormException(errno, errno_map[errno])

errno_map = {
    0: 'WORM_ERROR_NOERROR',
    1: 'WORM_ERROR_INVALID_PARAMETER',
    2: 'WORM_ERROR_NO_WORM_CARD',
    3: 'WORM_ERROR_IO',
    4: 'WORM_ERROR_TIMEOUT',
    5: 'WORM_ERROR_OUTOFMEM',
    6: 'WORM_ERROR_INVALID_RESPONSE',
    7: 'WORM_ERROR_STORE_FULL_INTERNAL',
    8: 'WORM_ERROR_RESPONSE_MISSING',
    9: 'WORM_ERROR_EXPORT_NOT_INITIALIZED',
    10: 'WORM_ERROR_EXPORT_FAILED',
    11: 'WORM_ERROR_INCREMENTAL_EXPORT_INVALID_STATE',
    12: 'WORM_ERROR_INCREMENTAL_EXPORT_NO_DATA',
    13: 'WORM_ERROR_POWER_CYCLE_DETECTED',
    14: 'WORM_ERROR_FIRMWARE_UPDATE_NOT_APPLIED',
    15: 'WORM_ERROR_THREAD_START_FAILED',
    16: 'WORM_ERROR_NETWORK',
    17: 'WORM_ERROR_CMD_NOT_SUPPORTED',
    18: 'WORM_ERROR_LAN_INVALID_API_TOKEN',
    19: 'WORM_ERROR_NETWORK_TIMEOUT',
    20: 'WORM_ERROR_CONNECTION_FAILED',
    21: 'WORM_ERROR_LAN_UNBALANCED_LOCKS',
    22: 'WORM_ERROR_LAN_INVALID_SERVER_RESPONSE',
    23: 'WORM_ERROR_INVALID_STATE',
    24: 'WORM_ERROR_TSE_NOT_FOUND',
    25: 'WORM_ERROR_INCREMENTAL_EXPORT_LIMIT_TOO_LOW',
    26: 'WORM_ERROR_FWU_NOT_AVAILABLE',
    0x1000: 'WORM_ERROR_FROM_CARD_FIRST',
    0x1001: 'WORM_ERROR_UNKNOWN',
    0x1002: 'WORM_ERROR_NO_TIME_SET',
    0x1004: 'WORM_ERROR_NO_TRANSACTION_IN_PROGRESS',
    0x1005: 'WORM_ERROR_INVALID_CMD_SYNTAX',
    0x1006: 'WORM_ERROR_NOT_ENOUGH_DATA_WRITTEN',
    0x1007: 'WORM_ERROR_TSE_INVALID_PARAMETER',
    0x1008: 'WORM_ERROR_TRANSACTION_NOT_STARTED',
    0x1009: 'WORM_ERROR_MAX_PARALLEL_TRANSACTIONS',
    0x100A: 'WORM_ERROR_CERTIFICATE_EXPIRED',
    0x100C: 'WORM_ERROR_NO_LAST_TRANSACTION',
    0x100D: 'WORM_ERROR_CMD_NOT_ALLOWED',
    0x100E: 'WORM_ERROR_TRANSACTION_SIGNATURES_EXCEEDED',
    0x100F: 'WORM_ERROR_NOT_AUTHORIZED',
    0x1010: 'WORM_ERROR_MAX_REGISTERED_CLIENTS_REACHED',
    0x1011: 'WORM_ERROR_CLIENT_NOT_REGISTERED',
    0x1012: 'WORM_ERROR_EXPORT_UNACKNOWLEDGED_DATA',
    0x1013: 'WORM_ERROR_CLIENT_HAS_UNFINISHED_TRANSACTIONS',
    0x1014: 'WORM_ERROR_TSE_HAS_UNFINISHED_TRANSACTIONS',
    0x1015: 'WORM_ERROR_TSE_NO_RESPONSE_TO_FETCH',
    0x1016: 'WORM_ERROR_NOT_ALLOWED_EXPORT_IN_PROGRESS',
    0x1017: 'WORM_ERROR_STORE_FULL',
    0x1050: 'WORM_ERROR_WRONG_STATE_NEEDS_PUK_CHANGE',
    0x1051: 'WORM_ERROR_WRONG_STATE_NEEDS_PIN_CHANGE',
    0x1053: 'WORM_ERROR_WRONG_STATE_NEEDS_ACTIVE_CTSS',
    0x1054: 'WORM_ERROR_WRONG_STATE_NEEDS_SELF_TEST',
    0x1055: 'WORM_ERROR_WRONG_STATE_NEEDS_SELF_TEST_PASSED',
    0x1061: 'WORM_ERROR_FWU_INTEGRITY_FAILURE',
    0x1062: 'WORM_ERROR_FWU_DECRYPTION_FAILURE',
    0x1064: 'WORM_ERROR_FWU_WRONG_FORMAT',
    0x1065: 'WORM_ERROR_FWU_INTERNAL_ERROR',
    0x1067: 'WORM_ERROR_FWU_DOWNGRADE_PROHIBITED',
    0x10FD: 'WORM_ERROR_TSE_ALREADY_INITIALIZED',
    0x10FE: 'WORM_ERROR_TSE_DECOMMISSIONED',
    0x10FF: 'WORM_ERROR_TSE_NOT_INITIALIZED',
    0x1100: 'WORM_ERROR_AUTHENTICATION_FAILED',
    0x1201: 'WORM_ERROR_AUTHENTICATION_PIN_BLOCKED',
    0x1202: 'WORM_ERROR_AUTHENTICATION_USER_NOT_LOGGED_IN',
    0x1300: 'WORM_ERROR_SELF_TEST_FAILED_FW',
    0x1310: 'WORM_ERROR_SELF_TEST_FAILED_CSP',
    0x1320: 'WORM_ERROR_SELF_TEST_FAILED_RNG',
    0x1400: 'WORM_ERROR_FWU_BASE_FW_ERROR',
    0x1500: 'WORM_ERROR_FWU_FWEXT_ERROR',
    0x1600: 'WORM_ERROR_FWU_CSP_ERROR',
    0x2001: 'WORM_ERROR_EXPORT_NONE_IN_PROGRESS',
    0x2002: 'WORM_ERROR_EXPORT_RETRY',
    0x2003: 'WORM_ERROR_EXPORT_NO_DATA_AVAILABLE',
    0xF000: 'WORM_ERROR_CMD_NOT_FOUND',
    0xFF00: 'WORM_ERROR_SIG_ERROR',
    0xFFFF: 'WORM_ERROR_FROM_CARD_LAST',
}
